<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-AJ4AGAI" name="com.crm.ContactsTest.CreateContactsformultipleDataTest" tests="1" failures="0" timestamp="1 Mar 2022 08:14:10 GMT" time="0.000" errors="1">
  <testcase name="createContactsformultipleData" time="0.000" classname="com.crm.ContactsTest.CreateContactsformultipleDataTest">
    <error type="org.testng.TestNGException" message="
Method public void com.crm.ContactsTest.CreateContactsformultipleDataTest.createContactsformultipleData(java.lang.String) throws java.lang.Throwable requires a @DataProvider named : OrgtestData">
      <![CDATA[org.testng.TestNGException: 
Method public void com.crm.ContactsTest.CreateContactsformultipleDataTest.createContactsformultipleData(java.lang.String) throws java.lang.Throwable requires a @DataProvider named : OrgtestData
	at org.testng.internal.Parameters.findDataProvider(Parameters.java:265)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:418)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1240)
	at org.testng.internal.Invoker.createParameters(Invoker.java:980)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1070)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </error>
  </testcase> <!-- createContactsformultipleData -->
</testsuite> <!-- com.crm.ContactsTest.CreateContactsformultipleDataTest -->
